[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NETLIFY_USE_YARN = "false"

# Clear cache if needed
[build.processing]
  skip_processing = false

# Redirect rules for single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
